// export { default as Header } from './Header'
export { default as HeroCarousel } from './HeroCarousel'
export { default as EventsSection } from './EventsSection'
export { default as PartnersSection } from './PartnersSection'
export { default as Footer } from './Footer'
